version: 2
project_name: BEpusdt
env:
  - GO111MODULE=on
builds:
  - env:
      - CGO_ENABLED=0
    main: ./main
    binary: bepusdt
    ldflags:
      - -s -w -buildid=
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - formats: [ tar.gz ]
    name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    files:
      - conf.example.toml
      - conf.simple.toml
      - install.sh
      - src: docs/bepusdt.service
        dst: .
        strip_parent: true
changelog:
  sort: asc
  filters:
    exclude: []
release:
  header: |
    ## 更新日志
